version: '3.9'

services:
  main_app:
    build:
      context: .
    container_name: main_app
    expose:
      - 8000
    command: "gunicorn core.project.wsgi:application --bind 0.0.0.0:8000"
    env_file:
        - ./.env
    depends_on:
      - postgres_db
    volumes:
      - .:/app
      - static_volume:/app/staticfiles

  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
        - ./.env

  elasticsearch:
    image: elasticsearch:7.17.22
    container_name: elasticsearch
    environment:
    - bootstrap.memory_lock=true
    - cluster.name=docker-cluster
    - cluster.routing.allocation.disk.threshold_enabled=false
    - discovery.type=single-node
    - ES_JAVA_OPTS=-XX:UseAVX=2 -Xms1g -Xmx1g
    - xpack.security.enabled=false
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
    - esdata:/usr/share/elasticsearch/data
    ports:
    - 9200:9200
    healthcheck:
      interval: 30s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'

  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - 1337:80
    depends_on:
      - main_app 
    volumes:
      - static_volume:/app/staticfiles

volumes:
  postgres_data:
  esdata:
    driver: local
  static_volume:
