# Generated by Django 5.1.3 on 2024-11-06 16:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('username', models.CharField(db_index=True, max_length=20, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Phone Number')),
                ('token', models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='User Token')),
                ('bio', models.CharField(blank=True, max_length=200)),
                ('role', models.CharField(choices=[('user', 'user'), ('admin', 'admin'), ('moderator', 'moderator')], default='user', max_length=10)),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
